files:
  - source: '*.md'
    translation: /%two_letters_code%/%original_file_name%
targets:
  - name: fgbgrfb
    sources:
      - /
    file: '%language%'
    format: android
    labels:
      - label
